- README.md
> adding peter's name

- README.md
> Added Zachs Name

- README.md
> added gary

- CONTRACT.md
I added the social contract guidelines decided so far.
> adding contract

- seed.js
- server/db/models/index.js
- server/db/models/product.js
- server/db/models/user.js
> added product model, add validation to user email, add seed file

- seed.js
> updated seed file

- .travis.yml
- README.md
- package-lock.json
- package.json
- public/index.html
API is deployed via heroku. Oauth is not working properly via heroku, but works via localhost.
> deployed via heroku

- package.json
- seed.js
- server/db/index.js
- server/db/models/cart.js
- server/db/models/index.js
> updated seed file and associations

- client/components/navbar.js
- server/db/models/index.js
> Changed name on the navbar and cartItem is now cartItems

- server/db/models/user.js
> CreateCart hook now works

- package-lock.json
- package.json
- seed.js
> chalk added heroku can now seed

- client/components/AllProducts.js
- client/store/product.js
- server/db/models/user.js
> Zachs render attempt

- client/components/AllProducts.js
- client/components/Product.js
> all products image and name working

- package-lock.json
- package.json
- public/index.html
> react-bootstrap is working

- client/components/Home.js
- client/components/SingleProduct.js
- client/components/navbar.js
- client/routes.js
- client/store/index.js
- client/store/singleProduct.js
- seed.js
- server/api/routes/products.js
> updated with home and single product page

- server/index.js
> made localhost a link

- client/components/AllProducts.js
Added a user to state on allProducts
> Added a user to  the state on AllProducts for example

- client/components/AllProducts.js
- client/routes.js
- server/api/routes/products.js
- server/api/routes/utils.js
- server/auth/index.js
- server/db/models/product.js
- server/db/models/user.js
> added some of jons changes

- client/components/SingleProduct.js
'single page loading without thunk'
> single page loading without thunk

- client/components/AllProducts.js
- client/components/Product.js
- client/components/SingleProduct.js
- seed.js
- server/db/models/cartItem.js
- server/db/models/index.js
- server/db/models/product.js
> added cartitem model and changed price from float to integer

- server/api/routes/users.js
- server/api/routes/utils.js
> got the cart api route to work

- server/api/index.js
- server/api/routes/carts.js
- server/api/routes/users.js
Got some of the api routes working
> some of the cart api is working

- server/api/routes/carts.js
Added a delete route to the carts api
> added a delete route tot he carts api

- client/store/currentCart.js
- client/store/pastCarts.js
- package-lock.json
> added addtocurrentcart reducer and delete function

- client/components/Cart.js
- client/store/index.js
- server/api/routes/carts.js
- server/db/models/cartItem.js
> cart component created

- client/components/SingleProduct.js
> added submit button funcionality to single product page

- client/components/Cart.js
- client/components/CartItems.js
- client/components/navbar.js
- client/routes.js
Added the cart to the front end
> added the cart on the front end

- client/components/SingleProduct.js
- client/store/currentCart.js
> cleaned up local state for button

- client/components/SingleProduct.js
- client/store/currentCart.js
> redirect to cart upon adding item to cart

- client/components/Cart.js
- client/components/CartItems.js
- client/store/currentCart.js
- server/api/routes/carts.js
> delete button workinmg

- client/components/Cart.js
> added some features

- client/components/CartItems.js
> edit cart item quantity drop down

- client/components/CartItems.js
> improved quantity drop down functionality

- server/api/routes/carts.js
> adding cart api updates

- client/components/CartItems.js
- client/store/currentCart.js
> linked put api route for edit cart dropdown functionality

- client/components/Cart.js
> added cart total info

- server/api/routes/carts.js
> Checkout route is working

- client/components/Cart.js
added continue shopping feature
> added continue shopping feature

- package-lock.json
- package.json
- server/api/routes/carts.js
- server/api/routes/utils.js
Got email confirmation working!!!!!
> Added a confirmation email upon checkout

- client/components/Cart.js
- client/components/Checkout.js
- client/routes.js
> added checkout page and order summary table

- client/components/navbar.js
- server/api/routes/carts.js
> added quantity to cart navbar

- client/components/Cart.js
- client/components/Checkout.js
- client/store/currentCart.js
> added checkout billing info

- client/components/Cart.js
> updated cart checkout button

- client/components/CartItems.js
- client/components/SingleProduct.js
> fixed baby code and scaled dropdown to match product stock

- client/app.js
- client/components/AllProducts.js
- client/components/Home.js
- client/components/Product.js
- client/components/SingleProduct.js
- client/components/auth-form.js
- client/components/index.js
- client/components/navbar.js
- client/store/user.js
- public/index.html
- public/style.css
- seed.js
- server/api/routes/carts.js
> We BOOTSRAPPIN!

- client/store/user.spec.js
- package-lock.json
- server/api/routes/users.js
> trying to get travis to work

- client/components/Cart.js
- client/components/CartItems.js
- client/components/navbar.js
- client/routes.js
- client/store/currentCart.js
- server/api/routes/carts.js
> got guest cart to work

- client/components/Cart.js
- client/components/CartItems.js
- public/style.css
> added design to cart

- client/components/Stripe.js
> fixing stripe for heroku

- client/components/Checkout.js
- client/routes.js
- server/api/routes/carts.js
> Guest Checkout Working

- client/components/Stripe.js
> updated stripe

- client/components/Checkout.js
> refresh working
